version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  nodets:
    build: .
    #ports:
    #  - "3000:3000"
    depends_on:
      - mongo
    environment:
      PORT: 3000
      JWTSecret: 233j90jf34pn2f2p4n3ng3nnp
      JWTLifetime: 30d
      dbConnectionURL: mongodb://root:example@mongo:27017

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
volumes:
  mongo-db: