version: "3"
services:
  nginx:
    ports:
    - 80:80
  nodets:
    expose:
      - 3000
    build: 
      context: .
      args:
        NODE_ENV: production
    command: npm start
    environment:
      - NODE_ENV=production

# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build