openapi: 3.0.0
info:
  title: NodeJS Express with TypeScript and Mongoose
  description: An effective nodejs express server implementation.
  version: 0.0.1
  contact:
    name: Samuel Ndirangu
    email: sndirangu7@gmail.com
servers:
  - url: https://nodets-playground.herokuapp.com/api/v1
    description: Optional server description, e.g. Main (production) server
  - url: https://ndirangu-nodets.azurewebsites.net/api/v1
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /products:
    get:
      summary: Returns a list of products.
      responses:
        '200': # status code
          description: A JSON array of products
          content:
            application/json:
              schema:
                type: array
